version: '3.8'
services: 
  web:
    environment:
      - DB_ECHO=False
      - DB_TRACK_MODIFICATIONS=False
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_TEST_HOST=test_db
      - DB_PORT=5432
      - DB_NAME=vending_machine
      - APP_CSRF_SESSION_KEY=c4df11e9-7b3c-4ce7-99c2-6da7a0f0cceb
      - APP_SECRET_KEY=35cf2b86-d4f7-4bd2-894f-c415b7da8edd
      - APP_JWT_SECRET_KEY=73807d3c-1c5f-4df3-b32d-fb41e299751f
    build:
      context: .
    ports:
    - 8000:5000
    volumes:
    - ./:/app
    depends_on: 
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vending_machine
    ports:
      - 8001:5432
  test_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vending_machine_test
    ports:
      - 8002:5432